env:
  es6: true
  node: true
  jest: true
extends:
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'sort-imports-es6-autofix'
  - 'prettier'
rules:
  no-shadow: 'off'
  '@typescript-eslint/no-shadow': ['error']
  no-unused-vars: 'off'
  no-use-before-define: 'off'
  no-undef: 'off'
  eol-last: ['error', 'always']
  comma-dangle: ['error', 'always-multiline']
  sort-imports-es6-autofix/sort-imports-es6: 'error'
  prettier/prettier: ['error']
